//! Build-time application configuration.
//!
//! Values are generated by `build.rs` from environment variables. This keeps
//! deployment-specific Wi-Fi credentials and MQTT broker addresses out of
//! repository source files.

include!(concat!(env!("OUT_DIR"), "/app_config.rs"));
